// Gmall-Frontend/lib/mock-data.ts

export const data2 = [
  {
    dataField1: true,
    dataField2: true,
    dataField3: true,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "95px",
    dataField6: false,
    dataField7: false,
    dataField8: false,
    dataField9: false,
    dataField10: "Quà tết",
    dataField11: "89px",
    dataField12: true,
  },
  {
    dataField1: true,
    dataField2: true,
    dataField3: true,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "95px",
    dataField6: false,
    dataField7: false,
    dataField8: false,
    dataField9: false,
    dataField10: "Quà tặng tốt nghiệp",
    dataField11: "89px",
    dataField12: true,
  },
  {
    dataField1: true,
    dataField2: true,
    dataField3: true,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "95px",
    dataField6: false,
    dataField7: false,
    dataField8: false,
    dataField9: false,
    dataField10: "Giáng Sinh",
    dataField11: "89px",
    dataField12: true,
  },
  {
    dataField1: true,
    dataField2: true,
    dataField3: true,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "95px",
    dataField6: false,
    dataField7: false,
    dataField8: false,
    dataField9: false,
    dataField10: "Valentine",
    dataField11: "89px",
    dataField12: true,
  },
  {
    dataField1: false,
    dataField2: false,
    dataField3: false,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "233px",
    dataField6: true,
    dataField7: true,
    dataField8: true,
    dataField9: true,
    dataField10: "Quà tặng thầy, cô",
    dataField11: "159px",
    dataField12: true,
  },
  {
    dataField1: false,
    dataField2: false,
    dataField3: false,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "213px",
    dataField6: true,
    dataField7: true,
    dataField8: true,
    dataField9: true,
    dataField10: "Quà tặng em bé",
    dataField11: "140px",
    dataField12: true,
  },
  {
    dataField1: false,
    dataField2: false,
    dataField3: false,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "209px",
    dataField6: true,
    dataField7: true,
    dataField8: true,
    dataField9: true,
    dataField10: "Quà tặng phụ nữ",
    dataField11: "145px",
    dataField12: true,
  },
  {
    dataField1: false,
    dataField2: false,
    dataField3: false,
    dataField4: "rgba(255,255,255,1)",
    dataField5: "232px",
    dataField6: true,
    dataField7: true,
    dataField8: true,
    dataField9: true,
    dataField10: "Quà tặng Business",
    dataField11: "162px",
    dataField12: true,
  },
  {
    dataField1: false,
    dataField2: false,
    dataField3: false,
    dataField4: "rgba(231,135,32,1)",
    dataField5: "276px",
    dataField6: true,
    dataField7: true,
    dataField8: true,
    dataField9: true,
    dataField10: "Blogs quà tặng & tin tức",
    dataField11: "211px",
    dataField12: false,
  },
];

export const data3 = [
  {
    dataField13: "/assets/ImageAsset118.png",
    dataField14: "Image Asset 118",
    dataField15: "538px",
    dataField16: true,
    dataField17: "266px",
    dataField18: "50",
    dataField19: false,
  },
  {
    dataField13: "/assets/ImageAsset119.png",
    dataField14: "Image Asset 119",
    dataField15: "543px",
    dataField16: false,
    dataField17: "426px",
    dataField18: "40",
    dataField19: true,
  },
  {
    dataField13: "/assets/ImageAsset120.png",
    dataField14: "Image Asset 120",
    dataField15: "546px",
    dataField16: false,
    dataField17: "110px",
    dataField18: "30",
    dataField19: true,
  },
  {
    dataField13: "/assets/ImageAsset121.png",
    dataField14: "Image Asset 121",
    dataField15: "547px",
    dataField16: false,
    dataField17: "0px",
    dataField18: "20",
    dataField19: true,
  },
  {
    dataField13: "/assets/ImageAsset122.png",
    dataField14: "Image Asset 122",
    dataField15: "547px",
    dataField16: false,
    dataField17: "545.8px",
    dataField18: "10",
    dataField19: true,
  },
];

export const data4 = [
  {
    dataField20: "81.1px",
    dataField21: "16px",
    dataField22: "Người nhận",
    dataField23: "85.4px",
    dataField24: "4.2px",
    dataField25: false,
    dataField26: "47px",
    dataField27: "Người nhận",
    dataField28: false,
    dataField29: false,
    dataField30: "/assets/SvgAsset103.svg",
    dataField31: "Svg Asset 103",
  },
  {
    dataField20: "75px",
    dataField21: "13px",
    dataField22: "Nhân dịp",
    dataField23: "83.2px",
    dataField24: "4.6px",
    dataField25: true,
    dataField26: "43px",
    dataField27: "Nhân dịp",
    dataField28: true,
    dataField29: false,
    dataField30: "/assets/SvgAsset102.svg",
    dataField31: "Svg Asset 102",
  },
  {
    dataField20: "75px",
    dataField21: "14px",
    dataField22: "Sở thích",
    dataField23: "84px",
    dataField24: "3.9px",
    dataField25: true,
    dataField26: "43px",
    dataField27: "Sở thích",
    dataField28: false,
    dataField29: true,
    dataField30: "/assets/SvgAsset101.svg",
    dataField31: "Svg Asset 101",
  },
  {
    dataField20: "72px",
    dataField21: "13px",
    dataField22: "Khoảng giá",
    dataField23: "83.1px",
    dataField24: "4.6px",
    dataField25: false,
    dataField26: "40px",
    dataField27: "Khoảng giá",
    dataField28: false,
    dataField29: false,
    dataField30: "/assets/SvgAsset100.svg",
    dataField31: "Svg Asset 100",
  },
];

export const data5 = [
  {
    dataField32: "40",
    dataField33: "/assets/ImageAsset98.png",
    dataField34: "Image Asset 98",
    dataField35: "/assets/SvgAsset89.svg",
    dataField36: "Svg Asset 89",
    dataField37: "Mũ snapback nam bí\n",
    dataField38: "207px",
    dataField39: true,
    dataField40: false,
    dataField41: "/assets/SvgAsset90.svg",
    dataField42: "Svg Asset 90",
    dataField43: "109.000 VND",
    dataField44: "149px",
    dataField45: "/assets/ImageAsset99.png",
    dataField46: "Image Asset 99",
  },
  {
    dataField32: "30",
    dataField33: "/assets/ImageAsset100.png",
    dataField34: "Image Asset 100",
    dataField35: "/assets/SvgAsset91.svg",
    dataField36: "Svg Asset 91",
    dataField37: "Quần dài form rộng\n",
    dataField38: "194px",
    dataField39: true,
    dataField40: false,
    dataField41: "/assets/SvgAsset92.svg",
    dataField42: "Svg Asset 92",
    dataField43: " 89.000 VND",
    dataField44: "144px",
    dataField45: "/assets/ImageAsset101.png",
    dataField46: "Image Asset 101",
  },
  {
    dataField32: "20",
    dataField33: "/assets/ImageAsset102.png",
    dataField34: "Image Asset 102",
    dataField35: "/assets/SvgAsset93.svg",
    dataField36: "Svg Asset 93",
    dataField37: "Áo phông nam Ralph \nLauren",
    dataField39: false,
    dataField40: true,
    dataField41: "/assets/SvgAsset94.svg",
    dataField42: "Svg Asset 94",
    dataField43: "205.000 VND",
    dataField44: "154px",
    dataField45: "/assets/ImageAsset103.png",
    dataField46: "Image Asset 103",
  },
  // ĐÃ SỬA: Thêm suffix _2 để tránh trùng key
  {
    dataField32: "20",
    dataField33: "/assets/ImageAsset102.png",
    dataField34: "Image Asset 102_2", 
    dataField35: "/assets/SvgAsset93.svg",
    dataField36: "Svg Asset 93",
    dataField37: "Áo phông nam Ralph \nLauren",
    dataField39: false,
    dataField40: true,
    dataField41: "/assets/SvgAsset94.svg",
    dataField42: "Svg Asset 94",
    dataField43: "205.000 VND",
    dataField44: "154px",
    dataField45: "/assets/ImageAsset103.png",
    dataField46: "Image Asset 103",
  },
  // ĐÃ SỬA: Thêm suffix _3 để tránh trùng key
  {
    dataField32: "20",
    dataField33: "/assets/ImageAsset102.png",
    dataField34: "Image Asset 102_3",
    dataField35: "/assets/SvgAsset93.svg",
    dataField36: "Svg Asset 93",
    dataField37: "Áo phông nam Ralph \nLauren",
    dataField39: false,
    dataField40: true,
    dataField41: "/assets/SvgAsset94.svg",
    dataField42: "Svg Asset 94",
    dataField43: "205.000 VND",
    dataField44: "154px",
    dataField45: "/assets/ImageAsset103.png",
    dataField46: "Image Asset 103",
  },
];

export const data6 = [
  { dataField47: "119px", dataField48: "Áo vest", dataField49: "67px" },
  { dataField47: "142px", dataField48: "Áo hoodie", dataField49: "90px" },
  { dataField47: "125px", dataField48: "Phụ kiện", dataField49: "73px" },
  { dataField47: "131px", dataField48: "Quần đùi", dataField49: "79px" },
];

export const data7 = [
  {
    dataField50: "40",
    dataField51: "/assets/ImageAsset87.png",
    dataField52: "Image Asset 87",
    dataField53: "/assets/SvgAsset79.svg",
    dataField54: "Svg Asset 79",
    dataField55: "Quần ống rộng vải nỉ\n",
    dataField56: "205px",
    dataField57: true,
    dataField59: "/assets/SvgAsset80.svg",
    dataField60: "Svg Asset 80",
    dataField61: "185.000 VND",
    dataField62: "148px",
    dataField63: "/assets/ImageAsset88.png",
    dataField64: "Image Asset 88",
  },
  {
    dataField50: "30",
    dataField51: "/assets/ImageAsset89.png",
    dataField52: "Image Asset 89",
    dataField53: "/assets/SvgAsset81.svg",
    dataField54: "Svg Asset 81",
    dataField55: "Quần ống siêu rộng\n",
    dataField56: "193px",
    dataField57: true,
    dataField59: "/assets/SvgAsset82.svg",
    dataField60: "Svg Asset 82",
    dataField61: "205.000 VND",
    dataField62: "154px",
    dataField63: "/assets/ImageAsset90.png",
    dataField64: "Image Asset 90",
  },
  {
    dataField50: "20",
    dataField51: "/assets/ImageAsset91.png",
    dataField52: "Image Asset 91",
    dataField53: "/assets/SvgAsset83.svg",
    dataField54: "Svg Asset 83",
    dataField55: "Áo nữ thắt eo ôm sát\nbody",
    dataField57: false,
    dataField58: "207px",
    dataField59: "/assets/SvgAsset84.svg",
    dataField60: "Svg Asset 84",
    dataField61: "85.000 VND",
    dataField62: "138px",
    dataField63: "/assets/ImageAsset92.png",
    dataField64: "Image Asset 92",
  },
  {
    dataField50: "10",
    dataField51: "/assets/ImageAsset93.png",
    dataField52: "Image Asset 93",
    dataField53: "/assets/SvgAsset85.svg",
    dataField54: "Svg Asset 85",
    dataField55: "Bộ đồ nữ quần đùi áo \nthun cộc tay",
    dataField57: false,
    dataField58: "215px",
    dataField59: "/assets/SvgAsset86.svg",
    dataField60: "Svg Asset 86",
    dataField61: "106.000 VND",
    dataField62: "149px",
    dataField63: "/assets/ImageAsset94.png",
    dataField64: "Image Asset 94",
  },
  // ĐÃ SỬA: Thêm suffix _2 để tránh trùng key
  {
    dataField50: "10",
    dataField51: "/assets/ImageAsset93.png",
    dataField52: "Image Asset 93_2",
    dataField53: "/assets/SvgAsset85.svg",
    dataField54: "Svg Asset 85",
    dataField55: "Bộ đồ nữ quần đùi áo \nthun cộc tay",
    dataField57: false,
    dataField58: "215px",
    dataField59: "/assets/SvgAsset86.svg",
    dataField60: "Svg Asset 86",
    dataField61: "106.000 VND",
    dataField62: "149px",
    dataField63: "/assets/ImageAsset94.png",
    dataField64: "Image Asset 94",
  },
];

export const data8 = [
  {
    dataField65: "132px",
    dataField66: "Quần dài",
    dataField67: "80px",
    dataField68: false,
  },
  {
    dataField65: "166px",
    dataField66: "Giày cao gót",
    dataField67: "114px",
    dataField68: false,
  },
  {
    dataField65: "113px",
    dataField66: "Váy",
    dataField67: "61px",
    dataField68: true,
  },
];

export const data9 = [
  {
    dataField69: "40",
    dataField70: "/assets/ImageAsset76.png",
    dataField71: "Image Asset 76",
    dataField72: "/assets/SvgAsset69.svg",
    dataField73: "Svg Asset 69",
    dataField74: "Đèn điện tử đuổi muỗi\n",
    dataField75: true,
    dataField76: true,
    dataField78: "/assets/SvgAsset70.svg",
    dataField79: "Svg Asset 70",
    dataField80: "389.000 VND",
    dataField81: "154px",
    dataField82: "/assets/ImageAsset77.png",
    dataField83: "Image Asset 77",
  },
  {
    dataField69: "30",
    dataField70: "/assets/ImageAsset78.png",
    dataField71: "Image Asset 78",
    dataField72: "/assets/SvgAsset71.svg",
    dataField73: "Svg Asset 71",
    dataField74: "Dụng cụ lấy ráy tai\nđiện tử",
    dataField75: false,
    dataField76: false,
    dataField77: "187px",
    dataField78: "/assets/SvgAsset72.svg",
    dataField79: "Svg Asset 72",
    dataField80: "125.000 VND",
    dataField81: "148px",
    dataField82: "/assets/ImageAsset79.png",
    dataField83: "Image Asset 79",
  },
  {
    dataField69: "20",
    dataField70: "/assets/ImageAsset80.png",
    dataField71: "Image Asset 80",
    dataField72: "/assets/SvgAsset73.svg",
    dataField73: "Svg Asset 73",
    dataField74: "Cân điện tử hình con \nHeo",
    dataField75: false,
    dataField76: false,
    dataField77: "209px",
    dataField78: "/assets/SvgAsset74.svg",
    dataField79: "Svg Asset 74",
    dataField80: "139.000 VND",
    dataField81: "148px",
    dataField82: "/assets/ImageAsset81.png",
    dataField83: "Image Asset 81",
  },
  {
    dataField69: "10",
    dataField70: "/assets/ImageAsset82.png",
    dataField71: "Image Asset 82",
    dataField72: "/assets/SvgAsset75.svg",
    dataField73: "Svg Asset 75",
    dataField74: "Máy massage xung \nđiện",
    dataField75: false,
    dataField76: false,
    dataField77: "197px",
    dataField78: "/assets/SvgAsset76.svg",
    dataField79: "Svg Asset 76",
    dataField80: "25.000 VND",
    dataField81: "138px",
    dataField82: "/assets/ImageAsset83.png",
    dataField83: "Image Asset 83",
  },
  // ĐÃ SỬA: Thêm suffix _2 để tránh trùng key
  {
    dataField69: "10",
    dataField70: "/assets/ImageAsset82.png",
    dataField71: "Image Asset 82_2",
    dataField72: "/assets/SvgAsset75.svg",
    dataField73: "Svg Asset 75",
    dataField74: "Máy massage xung \nđiện",
    dataField75: false,
    dataField76: false,
    dataField77: "197px",
    dataField78: "/assets/SvgAsset76.svg",
    dataField79: "Svg Asset 76",
    dataField80: "25.000 VND",
    dataField81: "138px",
    dataField82: "/assets/ImageAsset83.png",
    dataField83: "Image Asset 83",
  },
];

export const data10 = [
  {
    dataField84: "40",
    dataField85: "/assets/ImageAsset65.png",
    dataField86: "Image Asset 65",
    dataField87: "/assets/SvgAsset59.svg",
    dataField88: "Svg Asset 59",
    dataField89: "Miss bánh tráng, bánh\ntráng trộn vị chanh sả",
    dataField90: "223px",
    dataField92: false,
    dataField93: "/assets/SvgAsset60.svg",
    dataField94: "Svg Asset 60",
    dataField95: "50.000 VND",
    dataField96: "139px",
    dataField97: "/assets/ImageAsset66.png",
    dataField98: "Image Asset 66",
  },
  {
    dataField84: "30",
    dataField85: "/assets/ImageAsset67.png",
    dataField86: "Image Asset 67",
    dataField87: "/assets/SvgAsset61.svg",
    dataField88: "Svg Asset 61",
    dataField89: "Nama socola tươi 48\n",
    dataField91: "210px",
    dataField92: true,
    dataField93: "/assets/SvgAsset62.svg",
    dataField94: "Svg Asset 62",
    dataField95: "159.000 VND",
    dataField96: "148px",
    dataField97: "/assets/ImageAsset68.png",
    dataField98: "Image Asset 68",
  },
  {
    dataField84: "20",
    dataField85: "/assets/ImageAsset69.png",
    dataField86: "Image Asset 69",
    dataField87: "/assets/SvgAsset63.svg",
    dataField88: "Svg Asset 63",
    dataField89: "Bánh tráng trộn sẵn\n",
    dataField91: "199px",
    dataField92: true,
    dataField93: "/assets/SvgAsset64.svg",
    dataField94: "Svg Asset 64",
    dataField95: " 89.000 VND",
    dataField96: "144px",
    dataField97: "/assets/ImageAsset70.png",
    dataField98: "Image Asset 70",
  },
  {
    dataField84: "10",
    dataField85: "/assets/ImageAsset71.png",
    dataField86: "Image Asset 71",
    dataField87: "/assets/SvgAsset65.svg",
    dataField88: "Svg Asset 65",
    dataField89: "Combo bánh tráng\ntrộn",
    dataField90: "189px",
    dataField92: false,
    dataField93: "/assets/SvgAsset66.svg",
    dataField94: "Svg Asset 66",
    dataField95: "159.000 VND",
    dataField96: "148px",
    dataField97: "/assets/ImageAsset72.png",
    dataField98: "Image Asset 72",
  },
  // ĐÃ SỬA: Thêm suffix _2 để tránh trùng key
  {
    dataField84: "10",
    dataField85: "/assets/ImageAsset71.png",
    dataField86: "Image Asset 71_2",
    dataField87: "/assets/SvgAsset65.svg",
    dataField88: "Svg Asset 65",
    dataField89: "Combo bánh tráng\ntrộn",
    dataField90: "189px",
    dataField92: false,
    dataField93: "/assets/SvgAsset66.svg",
    dataField94: "Svg Asset 66",
    dataField95: "159.000 VND",
    dataField96: "148px",
    dataField97: "/assets/ImageAsset72.png",
    dataField98: "Image Asset 72",
  },
];

export const data11 = [
  {
    dataField99: "114px",
    dataField100: "Socola",
    dataField101: "62px",
    dataField102: true,
  },
  {
    dataField99: "161px",
    dataField100: "Hoa quả sấy",
    dataField101: "109px",
    dataField102: false,
  },
  {
    dataField99: "107px",
    dataField100: "Snack",
    dataField101: "55px",
    dataField102: true,
  },
];

export const data12 = [
  {
    dataField103: "40",
    dataField104: "/assets/ImageAsset54.png",
    dataField105: "Image Asset 54",
    dataField106: "/assets/SvgAsset49.svg",
    dataField107: "Svg Asset 49",
    dataField108: "Gel lông mày\n",
    dataField109: "130px",
    dataField110: true,
    dataField112: "/assets/SvgAsset50.svg",
    dataField113: "Svg Asset 50",
    dataField114: "/assets/ImageAsset55.png",
    dataField115: "Image Asset 55",
  },
  {
    dataField103: "30",
    dataField104: "/assets/ImageAsset56.png",
    dataField105: "Image Asset 56",
    dataField106: "/assets/SvgAsset51.svg",
    dataField107: "Svg Asset 51",
    dataField108: "Son tint bóng Romand\n",
    dataField109: "222px",
    dataField110: true,
    dataField112: "/assets/SvgAsset52.svg",
    dataField113: "Svg Asset 52",
    dataField114: "/assets/ImageAsset57.png",
    dataField115: "Image Asset 57",
  },
  {
    dataField103: "20",
    dataField104: "/assets/ImageAsset58.png",
    dataField105: "Image Asset 58",
    dataField106: "/assets/SvgAsset53.svg",
    dataField107: "Svg Asset 53",
    dataField108: "Lược massage Hello\nKitty",
    dataField110: false,
    dataField111: "203px",
    dataField112: "/assets/SvgAsset54.svg",
    dataField113: "Svg Asset 54",
    dataField114: "/assets/ImageAsset59.png",
    dataField115: "Image Asset 59",
  },
  {
    dataField103: "10",
    dataField104: "/assets/ImageAsset60.png",
    dataField105: "Image Asset 60",
    dataField106: "/assets/SvgAsset55.svg",
    dataField107: "Svg Asset 55",
    dataField108: "Máy kẹp tóc mini Tiện\nlợi",
    dataField110: false,
    dataField111: "218px",
    dataField112: "/assets/SvgAsset56.svg",
    dataField113: "Svg Asset 56",
    dataField114: "/assets/ImageAsset61.png",
    dataField115: "Image Asset 61",
  },
  // ĐÃ SỬA: Thêm suffix _2 để tránh trùng key
  {
    dataField103: "10",
    dataField104: "/assets/ImageAsset60.png",
    dataField105: "Image Asset 60_2",
    dataField106: "/assets/SvgAsset55.svg",
    dataField107: "Svg Asset 55",
    dataField108: "Máy kẹp tóc mini Tiện\nlợi",
    dataField110: false,
    dataField111: "218px",
    dataField112: "/assets/SvgAsset56.svg",
    dataField113: "Svg Asset 56",
    dataField114: "/assets/ImageAsset61.png",
    dataField115: "Image Asset 61",
  },
];

export const data13 = [
  {
    dataField116: "159px",
    dataField117: "Sữa rửa mặt",
    dataField118: "107px",
    dataField119: false,
  },
  {
    dataField116: "102px",
    dataField117: "Toner",
    dataField118: "50px",
    dataField119: true,
  },
  {
    dataField116: "113px",
    dataField117: "Mặt nạ",
    dataField118: "61px",
    dataField119: false,
  },
  {
    dataField116: "108px",
    dataField117: "Serum",
    dataField118: "56px",
    dataField119: true,
  },
];

export const data15 = [
  {
    dataField182: "40",
    dataField183: "/assets/ImageAsset43.png",
    dataField184: "Image Asset 43",
    dataField185: "/assets/SvgAsset39.svg",
    dataField186: "Svg Asset 39",
    dataField187: "Đèn ngủ 3d trang trí\n",
    dataField188: "202px",
    dataField189: "/assets/SvgAsset40.svg",
    dataField190: "Svg Asset 40",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset44.png",
    dataField194: "Image Asset 44",
  },
  {
    dataField182: "30",
    dataField183: "/assets/ImageAsset45.png",
    dataField184: "Image Asset 45",
    dataField185: "/assets/SvgAsset41.svg",
    dataField186: "Svg Asset 41",
    dataField187: "Gối công thái học \n",
    dataField188: "182px",
    dataField189: "/assets/SvgAsset42.svg",
    dataField190: "Svg Asset 42",
    dataField191: false,
    dataField192: false,
    dataField193: "/assets/ImageAsset46.png",
    dataField194: "Image Asset 46",
  },
  {
    dataField182: "20",
    dataField183: "/assets/ImageAsset47.png",
    dataField184: "Image Asset 47",
    dataField185: "/assets/SvgAsset43.svg",
    dataField186: "Svg Asset 43",
    dataField187: "10 bịch giấy đa năng\n",
    dataField188: "207px",
    dataField189: "/assets/SvgAsset44.svg",
    dataField190: "Svg Asset 44",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset48.png",
    dataField194: "Image Asset 48",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  // ĐÃ SỬA: Thêm suffix _2..._8 để tránh trùng key
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_2",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_3",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_4",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_5",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_6",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
  {
    dataField182: "10",
    dataField183: "/assets/ImageAsset49.png",
    dataField184: "Image Asset 49_7",
    dataField185: "/assets/SvgAsset45.svg",
    dataField186: "Svg Asset 45",
    dataField187: "Ô dù che mưa gấp gọn\n",
    dataField188: "224px",
    dataField189: "/assets/SvgAsset46.svg",
    dataField190: "Svg Asset 46",
    dataField191: true,
    dataField192: true,
    dataField193: "/assets/ImageAsset50.png",
    dataField194: "Image Asset 50",
  },
];

export const data14 = [
  {
    dataField120: "/assets/ImageAsset31.png",
    dataField121: "Image Asset 31",
    dataField122: "Giấy vệ sinh cuộn lớn\n",
    dataField123: "210px",
    dataField124: "/assets/SvgAsset29.svg",
    dataField125: "Svg Asset 29",
    dataField126: "/assets/ImageAsset32.png",
    dataField127: "Image Asset 32",
    dataField128: "/assets/ImageAsset33.png",
    dataField129: "Image Asset 33",
    dataField130: "/assets/SvgAsset30.svg",
    dataField131: "Svg Asset 30",
    dataField132: "Combo 100 giấy dán\nanime",
    dataField133: "207px",
    dataField134: false,
    dataField135: false,
    dataField136: "/assets/SvgAsset31.svg",
    dataField137: "Svg Asset 31",
    dataField138: true,
    dataField139: true,
    dataField140: "/assets/ImageAsset34.png",
    dataField141: "Image Asset 34",
    dataField142: "/assets/ImageAsset35.png",
    dataField143: "Image Asset 35",
    dataField144: "/assets/SvgAsset32.svg",
    dataField145: "Svg Asset 32",
    dataField146: "Áo sơ mi croptop kẻ\n",
    dataField147: "201px",
    dataField148: true,
    dataField149: false,
    dataField150: "/assets/SvgAsset33.svg",
    dataField151: "Svg Asset 33",
    dataField152: "58.898 VND",
    dataField153: "137px",
    dataField154: "/assets/ImageAsset36.png",
    dataField155: "Image Asset 36",
    dataField156: "/assets/ImageAsset37.png",
    dataField157: "Image Asset 37",
    dataField158: "/assets/SvgAsset34.svg",
    dataField159: "Svg Asset 34",
    dataField160: "Áo sơ mi nữ dáng rộng\n",
    dataField161: "221px",
    dataField162: true,
    dataField164: "/assets/SvgAsset35.svg",
    dataField165: "Svg Asset 35",
    dataField166: "289.000 VND",
    dataField167: "153px",
    dataField168: "/assets/ImageAsset38.png",
    dataField169: "Image Asset 38",
    dataField170: "/assets/ImageAsset39.png",
    dataField171: "Image Asset 39",
    dataField172: "/assets/SvgAsset36.svg",
    dataField173: "Svg Asset 36",
    dataField174: "Bộ sạc nhanh 20W \n",
    dataField175: "192px",
    dataField176: "/assets/SvgAsset37.svg",
    dataField177: "Svg Asset 37",
    dataField178: true,
    dataField179: true,
    dataField180: "/assets/ImageAsset40.png",
    dataField181: "Image Asset 40",
  },
  {
    dataField120: "/assets/ImageAsset21.png",
    dataField121: "Image Asset 21",
    dataField122: "Ghế công thái học \n",
    dataField123: "187px",
    dataField124: "/assets/SvgAsset20.svg",
    dataField125: "Svg Asset 20",
    dataField126: "/assets/ImageAsset22.png",
    dataField127: "Image Asset 22",
    dataField128: "/assets/ImageAsset23.png",
    dataField129: "Image Asset 23",
    dataField130: "/assets/SvgAsset21.svg",
    dataField131: "Svg Asset 21",
    dataField132: "Nút bắn pubg, freefire\n...",
    dataField133: "222px",
    dataField134: false,
    dataField135: false,
    dataField136: "/assets/SvgAsset22.svg",
    dataField137: "Svg Asset 22",
    dataField138: false,
    dataField139: false,
    dataField140: "/assets/ImageAsset24.png",
    dataField141: "Image Asset 24",
    dataField142: "/assets/ImageAsset25.png",
    dataField143: "Image Asset 25",
    dataField144: "/assets/SvgAsset23.svg",
    dataField145: "Svg Asset 23",
    dataField146: "Túi đeo vai chéo nữ\n",
    dataField147: "193px",
    dataField148: true,
    dataField149: false,
    dataField150: "/assets/SvgAsset24.svg",
    dataField151: "Svg Asset 24",
    dataField152: "289.000 VND",
    dataField153: "153px",
    dataField154: "/assets/ImageAsset26.png",
    dataField155: "Image Asset 26",
    dataField156: "/assets/ImageAsset27.png",
    dataField157: "Image Asset 27",
    dataField158: "/assets/SvgAsset25.svg",
    dataField159: "Svg Asset 25",
    dataField160: "Khô gà lá chanh chà\nbông",
    dataField162: false,
    dataField163: "204px",
    dataField164: "/assets/SvgAsset26.svg",
    dataField165: "Svg Asset 26",
    dataField166: " 15.000 VND",
    dataField167: "138px",
    dataField168: "/assets/ImageAsset28.png",
    dataField169: "Image Asset 28",
    dataField170: "/assets/ImageAsset29.png",
    dataField171: "Image Asset 29",
    dataField172: "/assets/SvgAsset27.svg",
    dataField173: "Svg Asset 27",
    dataField174: "Áo sweater hello kitty\n",
    dataField175: "221px",
    dataField176: "/assets/SvgAsset28.svg",
    dataField177: "Svg Asset 28",
    dataField178: true,
    dataField179: true,
    dataField180: "/assets/ImageAsset30.png",
    dataField181: "Image Asset 30",
  },
  {
    dataField120: "/assets/ImageAsset11.png",
    dataField121: "Image Asset 11",
    dataField122: "Miếng xốp melamine\n",
    dataField123: "205px",
    dataField124: "/assets/SvgAsset11.svg",
    dataField125: "Svg Asset 11",
    dataField126: "/assets/ImageAsset12.png",
    dataField127: "Image Asset 12",
    dataField128: "/assets/ImageAsset13.png",
    dataField129: "Image Asset 13",
    dataField130: "/assets/SvgAsset12.svg",
    dataField131: "Svg Asset 12",
    dataField132: "Xe máy Honda Sh 125i\nAbs",
    dataField133: "221px",
    dataField134: false,
    dataField135: false,
    dataField136: "/assets/SvgAsset13.svg",
    dataField137: "Svg Asset 13",
    dataField138: true,
    dataField139: true,
    dataField140: "/assets/ImageAsset14.png",
    dataField141: "Image Asset 14",
    dataField142: "/assets/ImageAsset15.png",
    dataField143: "Image Asset 15",
    dataField144: "/assets/SvgAsset14.svg",
    dataField145: "Svg Asset 14",
    dataField146: "Xe máy điện vinfast\n",
    dataField147: "198px",
    dataField148: true,
    dataField149: false,
    dataField150: "/assets/SvgAsset15.svg",
    dataField151: "Svg Asset 15",
    dataField152: "14.289.000 VND",
    dataField153: "186px",
    dataField154: "/assets/ImageAsset16.png",
    dataField155: "Image Asset 16",
    dataField156: "/assets/ImageAsset17.png",
    dataField157: "Image Asset 17",
    dataField158: "/assets/SvgAsset16.svg",
    dataField159: "Svg Asset 16",
    dataField160: "[AURANE] chính hãng\nGel vuốt tóc giữ nếp l..",
    dataField162: false,
    dataField163: "224px",
    dataField164: "/assets/SvgAsset17.svg",
    dataField165: "Svg Asset 17",
    dataField166: "190.000 VND",
    dataField167: "149px",
    dataField168: "/assets/ImageAsset18.png",
    dataField169: "Image Asset 18",
    dataField170: "/assets/ImageAsset19.png",
    dataField171: "Image Asset 19",
    dataField172: "/assets/SvgAsset18.svg",
    dataField173: "Svg Asset 18",
    dataField174: "iPhone 14 chính hãng\n",
    dataField175: "211px",
    dataField176: "/assets/SvgAsset19.svg",
    dataField177: "Svg Asset 19",
    dataField178: false,
    dataField179: false,
    dataField180: "/assets/ImageAsset20.png",
    dataField181: "Image Asset 20",
  },
  {
    dataField120: "/assets/ImageAsset1.png",
    dataField121: "Image Asset 1",
    dataField122: "Bộ phát không dây \n",
    dataField123: "194px",
    dataField124: "/assets/SvgAsset2.svg",
    dataField125: "Svg Asset 2",
    dataField126: "/assets/ImageAsset2.png",
    dataField127: "Image Asset 2",
    dataField128: "/assets/ImageAsset3.png",
    dataField129: "Image Asset 3",
    dataField130: "/assets/SvgAsset3.svg",
    dataField131: "Svg Asset 3",
    dataField132: "Móc treo chìa khoá \n",
    dataField134: true,
    dataField135: true,
    dataField136: "/assets/SvgAsset4.svg",
    dataField137: "Svg Asset 4",
    dataField138: true,
    dataField139: true,
    dataField140: "/assets/ImageAsset4.png",
    dataField141: "Image Asset 4",
    dataField142: "/assets/ImageAsset5.png",
    dataField143: "Image Asset 5",
    dataField144: "/assets/SvgAsset5.svg",
    dataField145: "Svg Asset 5",
    dataField146: "Muôi xới cơm độc lạ\nmuôi xới cơm lật đ..",
    dataField148: false,
    dataField149: true,
    dataField150: "/assets/SvgAsset6.svg",
    dataField151: "Svg Asset 6",
    dataField152: " 14.200 VND",
    dataField153: "138px",
    dataField154: "/assets/ImageAsset6.png",
    dataField155: "Image Asset 6",
    dataField156: "/assets/ImageAsset7.png",
    dataField157: "Image Asset 7",
    dataField158: "/assets/SvgAsset7.svg",
    dataField159: "Svg Asset 7",
    dataField160: "Bàn trà gỗ 4 chân\n",
    dataField161: "179px",
    dataField162: true,
    dataField164: "/assets/SvgAsset8.svg",
    dataField165: "Svg Asset 8",
    dataField166: "289.000 VND",
    dataField167: "153px",
    dataField168: "/assets/ImageAsset8.png",
    dataField169: "Image Asset 8",
    dataField170: "/assets/ImageAsset9.png",
    dataField171: "Image Asset 9",
    dataField172: "/assets/SvgAsset9.svg",
    dataField173: "Svg Asset 9",
    dataField174: "Chuột gaming G102\n",
    dataField175: "198px",
    dataField176: "/assets/SvgAsset10.svg",
    dataField177: "Svg Asset 10",
    dataField178: true,
    dataField179: true,
    dataField180: "/assets/ImageAsset10.png",
    dataField181: "Image Asset 10",
  },
];

export const data16 = [
  {
    dataField195: "Về chúng tôi",
    dataField196: "119px",
    dataField197: true,
    dataField198: true,
  },
  {
    dataField195: "Giới thiệu về LoveGifts Việt Nam",
    dataField196: "306px",
    dataField197: false,
    dataField198: false,
    dataField199: "10px",
  },
  {
    dataField195: "Tuyển dụng",
    dataField196: "106px",
    dataField197: false,
    dataField198: false,
    dataField199: "8px",
  },
  {
    dataField195: "Điều khoản & Chính sách bảo mật",
    dataField196: "312px",
    dataField197: false,
    dataField198: false,
    dataField199: "12px",
  },
  {
    dataField195: "Hợp tác cùng LoveGifts",
    dataField196: "222px",
    dataField197: false,
    dataField198: false,
    dataField199: "11px",
  },
  {
    dataField195: "Câu chuyện thương hiệu",
    dataField196: "222px",
    dataField197: false,
    dataField198: false,
    dataField199: "12px",
  },
  {
    dataField195: "Liên hệ & Hỗ trợ khách hàng",
    dataField196: "259px",
    dataField197: false,
    dataField198: false,
    dataField199: "12px",
  },
];

export const data17 = [
  {
    dataField200: "Hợp tác và liên kết",
    dataField201: "238.2px",
    dataField202: true,
    dataField203: true,
  },
  {
    dataField200: "Quy chế hoạt động",
    dataField201: "210.5px",
    dataField202: false,
    dataField203: false,
    dataField204: "16.5px",
  },
  {
    dataField200: "Hợp tác bán hàng",
    dataField201: "179.2px",
    dataField202: false,
    dataField203: false,
    dataField204: "14.3px",
  },
  {
    dataField200: "Tin tức",
    dataField201: "156.4px",
    dataField202: false,
    dataField203: false,
    dataField204: "13.3px",
  },
];

export const data18 = [
  {
    dataField205: "/assets/ImageAsset132.png",
    dataField206: "Image Asset 132",
  },
  {
    dataField205: "/assets/ImageAsset131.png",
    dataField206: "Image Asset 131",
  },
  {
    dataField205: "/assets/ImageAsset130.png",
    dataField206: "Image Asset 130",
  },
  {
    dataField205: "/assets/ImageAsset129.png",
    dataField206: "Image Asset 129",
  },
];

export const data19 = [
  {
    dataField207: "/assets/ImageAsset135.png",
    dataField208: "Image Asset 135",
    dataField209: "64px",
    dataField210: "17px",
  },
  {
    dataField207: "/assets/ImageAsset134.png",
    dataField208: "Image Asset 134",
    dataField209: "43px",
    dataField210: "31px",
    dataField211: "9.3px",
  },
  {
    dataField207: "/assets/ImageAsset133.png",
    dataField208: "Image Asset 133",
    dataField209: "38px",
    dataField210: "23px",
    dataField211: "11px",
  },
  {
    dataField207: "/assets/ImageAsset136.png",
    dataField208: "Image Asset 136",
    dataField209: "25px",
    dataField210: "25px",
    dataField211: "11px",
  },
];

export const productSortChips = [
  {
    id: "all",
    label: "TẤT CẢ",
    minWidth: "118px",
    isActive: true,
  },
  {
    id: "pants",
    label: "Quần",
    minWidth: "100px",
    isActive: false,
  },
  {
    id: "shirt",
    label: "Áo Sơ mi",
    minWidth: "129px",
    isActive: false,
  },
  {
    id: "shoes",
    label: "Giày",
    minWidth: "93px",
    isActive: false,
  },
  {
    id: "sandals",
    label: "Dép",
    minWidth: "88px",
    isActive: false,
  },
  {
    id: "socks",
    label: "Tất",
    minWidth: "82px",
    isActive: false,
  },
  {
    id: "accessories",
    label: "Phụ kiện",
    minWidth: "125px",
    isActive: false,
  },
];

export const filterLocations = [
  { id: "hanoi", label: "Hà Nội" },
  { id: "hcm", label: "TP. Hồ Chí Minh" },
  { id: "hadong", label: "Quận Hà Đông" },
  { id: "hoangmai", label: "Quận Hoàng Mai" },
];

export const filterCategories = [
  { id: "blazer", label: "Blazer" },
  { id: "vest", label: "Vest" },
  { id: "somi", label: "Áo Sơ Mi" },
  { id: "thun", label: "Áo Thun" },
];

export const filterShipping = [
  { id: "express", label: "Hoả Tốc" },
  { id: "fast", label: "Nhanh" },
  { id: "save", label: "Tiết Kiệm" },
];

export const filterBrands = [
  { id: "adidas", label: "Adidas" },
  { id: "nike", label: "Nike" },
  { id: "prada", label: "Prada" },
  { id: "lv", label: "Louis Vuitton" },
  { id: "boo", label: "BOO" },
];

export const filterRatings = [5, 4, 3, 2, 1]; // Data cho 5, 4, 3, 2, 1 sao

export const filterServices = [
  { id: "sale", label: "Đang Giảm Giá" },
  { id: "freeship", label: "Miễn Phí Vận Chuyển" },
  { id: "flashsale", label: "Xả Hàng Giá Sốc" },
];

type ProductVariant = "flash-sale" | "regular";

// Gộp data11, 12, 13 thành 1 mảng
export const productGridItems = [
  // From data11 (Original Items)
  {
    id: "p1",
    sellerId: "seller-001",
    variant: "flash-sale" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset20.png",
    title: "Áo sơ mi nam kiểu dáng basic khoác..",
    price: "199.000 VND", 
    discountPercent: "-31%",
    countdown: { hours: '01', minutes: '45', seconds: '56' },
    stockRemaining: 15,
    stockTotal: 50,
  },
  {
    id: "p2",
    sellerId: "seller-001",
    variant: "flash-sale" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset22.png",
    title: "Quần đùi nam chính hãng",
    price: "159.000 VND",
    discountPercent: "-20%",
    countdown: { hours: '02', minutes: '30', seconds: '12' },
    stockRemaining: 8,
    stockTotal: 30,
  },
  {
    id: "p3",
    sellerId: "seller-001",
    variant: "flash-sale" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset24.png",
    title: "Áo thun hiphop",
    price: "200.000 VND",
    discountPercent: "-20%",
    countdown: { hours: '00', minutes: '59', seconds: '05' },
    stockRemaining: 22,
    stockTotal: 100,
  },
  {
    id: "p4",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset26.png",
    title: "Áo thun ngắn tay localbrand",
    regularPrice: "320.000 VND",
    smallTag: "Giảm 15K",
    salesCount: "5.1K",
    rating: 4.9,
    location: "Đà Nẵng",
  },
  {
    id: "p5",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset12.png",
    title: "Áo sơ mi nam kiểu dáng basic khoác..",
    regularPrice: "289.000 VND",
    smallTag: "Giảm 5K",
    salesCount: "750",
    rating: 4.6,
    location: "Hà Nội",
  },
  {
    id: "p6",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset14.png",
    title: "Quần đùi nam chính hãng",
    regularPrice: "199.000 VND",
    smallTag: "Giảm 10K",
    salesCount: "2.2K",
    rating: 4.8,
    location: "TP. Hồ Chí Minh",
  },
  // ... (Giữ các item p7 -> p12 cũ)
  {
    id: "p7",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset16.png",
    title: "Áo thun hiphop",
    regularPrice: "250.000 VND",
    smallTag: "Giảm 5K",
    salesCount: "920",
    rating: 4.7,
    location: "Hà Nội",
  },
  {
    id: "p8",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset18.png",
    title: "Áo thun ngắn tay localbrand",
    regularPrice: "320.000 VND",
    smallTag: "Giảm 15K",
    salesCount: "1.8K",
    rating: 4.9,
    location: "Đà Nẵng",
  },
  {
    id: "p9",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset4.png",
    title: "Thắt lưng mặt xoay nam",
    regularPrice: "450.000 VND",
    smallTag: "Giảm 25K",
    salesCount: "1.1K",
    rating: 4.9,
    location: "Hà Nội",
  },
  {
    id: "p10",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset6.png",
    title: "Áo thun chất lượng cao nhập khẩu ch..",
    regularPrice: "300.000 VND",
    smallTag: "Giảm 5K",
    salesCount: "4.3K",
    rating: 4.8,
    location: "TP. Hồ Chí Minh",
  },
  {
    id: "p11",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset8.png",
    title: "Áo thun cộc tay nam ralph lauren",
    regularPrice: "500.000 VND",
    smallTag: "Giảm 50K",
    salesCount: "980",
    rating: 4.9,
    location: "Hà Nội",
  },
  {
    id: "p12",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset10.png",
    title: "Mũ lưỡi trai LA thời trang hiphop..",
    regularPrice: "150.000 VND",
    smallTag: "Giảm 5K",
    salesCount: "10.2K",
    rating: 4.9,
    location: "TP. Hồ Chí Minh",
  },
  // MOCK THÊM DỮ LIỆU SẢN PHẨM LIÊN QUAN (p13 -> p20)
  {
    id: "p13",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset20.png",
    title: "Quần Jeans nam ống đứng cao cấp",
    regularPrice: "450.000 VND",
    smallTag: "Freeship",
    salesCount: "3.5K",
    rating: 5.0,
    location: "Hà Nội",
  },
  {
    id: "p14",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset22.png",
    title: "Áo Polo nam vải cá sấu",
    regularPrice: "220.000 VND",
    smallTag: "Mua 2 giảm 10%",
    salesCount: "8.9K",
    rating: 4.7,
    location: "Hải Phòng",
  },
  {
    id: "p15",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset24.png",
    title: "Giày Sneaker nam trắng basic",
    regularPrice: "350.000 VND",
    smallTag: "Hot",
    salesCount: "1.2K",
    rating: 4.5,
    location: "Hà Nội",
  },
  {
    id: "p16",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset26.png",
    title: "Tất nam cổ cao khử mùi (Set 5)",
    regularPrice: "50.000 VND",
    smallTag: "Rẻ vô địch",
    salesCount: "20K",
    rating: 5.0,
    location: "TP. Hồ Chí Minh",
  },
  {
    id: "p17",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset12.png",
    title: "Ví da nam cầm tay thời trang",
    regularPrice: "550.000 VND",
    smallTag: "Quà tặng",
    salesCount: "400",
    rating: 4.8,
    location: "Đà Nẵng",
  },
  {
    id: "p18",
    sellerId: "seller-001",
    variant: "regular" as ProductVariant,
    imageUrl: "/assets-product/ImageAsset14.png",
    title: "Kính mát nam phân cực chống UV",
    regularPrice: "180.000 VND",
    smallTag: "Xả kho",
    salesCount: "2.1K",
    rating: 4.6,
    location: "Hà Nội",
  },
];

// Thêm vào cuối file: src/lib/mock-data.ts

export const productDetailVouchers = [
  {
    id: "v1",
    icon: "/assets-product-details/SvgAsset30.svg",
    text: "Tặng phiếu mua hàng 100,000đ",
  },
  {
    id: "v2",
    icon: "/assets-product-details/SvgAsset29.svg",
    text: "Miễn phí vận chuyển cho đơn hàng từ 200,000đ",
  },
  {
    id: "v3",
    icon: "/assets-product-details/SvgAsset28.svg",
    text: "Giảm 10% cho thành viên mới",
  },
];

export const colorOptions = [
  { color: "rgba(241,0,0,1)", name: "Đỏ", id: "red" },
  { color: "rgba(0,241,20,1)", name: "Xanh", id: "green" },
  { color: "rgba(253,91,183,1)", name: "Hồng", id: "pink" },
  { color: "rgba(241,141,0,1)", name: "Cam", id: "orange" },
];

export const sizeOptions = [
  { name: "XS", id: "xs" },
  { name: "S", id: "s" },
  { name: "M", id: "m" },
  { name: "L", id: "l" },
];

export const productImages = [
  "/assets-product-details/ImageAsset28.png", // Ảnh chính
  "/assets-product-details/ImageAsset27.png",
  "/assets-product-details/ImageAsset26.png",
  "/assets-product-details/ImageAsset25.png",
  "/assets-product-details/ImageAsset24.png",
];

export const shopInfoStats = {
  left: [
    "Sản phẩm: 2,4K",
    "Đang Theo: 5",
    "Tỉ lệ phản hồi Chat: 100% (trong vài giờ)",
  ],
  right: [
    "Người theo dõi: 2,4K",
    "Đánh giá: 1,1 ( 2k đánh giá )",
    "Tham gia: 5 năm trước",
  ],
};

export const sidebarVouchers = [
  {
    id: "sv1",
    title: "Giảm 20k tối thiểu đơn 99k",
    expiry: "HSD: 16/05/2026",
    cta: "Lưu",
  },
  {
    id: "sv2",
    title: "Giảm 50k tối thiểu đơn 500k",
    expiry: "HSD: 20/05/2026",
    cta: "Lưu",
  },
];

export const promoComboProducts = [
  {
    id: "pc1",
    imageUrl: "/assets-product-details/ImageAsset21.png",
    title: "Tất thể thao cổ ngắn chống trơn trượt ch...",
    price: "230.000 VND"
  },
  {
    id: "pc2",
    imageUrl: "/assets-product-details/ImageAsset22.png",
    title: "Tất thể thao cổ ngắn chống trơn trượt ch...",
    price: "230.000 VND"
  }
];
import { MegaMenuData } from "@/types/navigation";

export const megaMenuData: MegaMenuData = {
  // --- CỘT TRÁI (SIDEBAR) ---
  sidebarNav: [
    { id: "1", label: "NGƯỜI NHẬN", isActive: true },
    { id: "2", label: "NHÂN DỊP", isActive: false },
    { id: "3", label: "BUSINESS GIFTS", isActive: false },
    { id: "4", label: "TƯ VẤN TẶNG QUÀ", isActive: false },
  ],
  brandLogosLeft: [
    { id: "b1", alt: "PNJ", imageUrl: "/assets/logos/viettel.png" }, 
    { id: "b2", alt: "Fahasa", imageUrl: "/assets/logos/realme.png" },
    { id: "b3", alt: "Lock&Lock", imageUrl: "/assets/logos/mobell.png" },
    { id: "b4", alt: "Hasaki", imageUrl: "/assets/logos/tcl.png" },
  ],
  categoriesLeft: [
    { id: "c1", label: "Gói quà nghệ thuật", icon: "gift-icon" },
    { id: "c2", label: "Thiệp chúc mừng", icon: "card-icon" },
    { id: "c3", label: "Hoa tươi", icon: "flower-icon" },
  ],
  rightSidebarItems: [
    { id: "r1", label: "Flash Sale", imageUrl: "" },
    { id: "r2", label: "Mã giảm giá", imageUrl: "" },
    { id: "r3", label: "Xu hướng quà tặng", imageUrl: "" },
  ],

  // --- NỘI DUNG ĐỘNG THEO TAB ---
  contents: {
    // === TAB 1: NGƯỜI NHẬN ===
    "1": {
      brandLogosTop: [
        { id: "m1", alt: "Pampers", imageUrl: "/assets/logos/iphone.png" }, // Placeholder img
        { id: "m2", alt: "Lego", imageUrl: "/assets/logos/samsung.png" },
        { id: "m3", alt: "Ensure", imageUrl: "/assets/logos/xiaomi.png" },
        { id: "m4", alt: "Laneige", imageUrl: "/assets/logos/oppo.png" },
        { id: "m5", alt: "Owen", imageUrl: "/assets/logos/nokia.png" },
      ],
      featuredProducts: [
        { id: "p1", title: "Set quà sơ sinh cao cấp Bamboo...", imageUrl: "/assets/p1.png", href: "#", price: "599.000đ" },
        { id: "p2", title: "Máy massage cổ vai gáy cho người già...", imageUrl: "/assets/p2.png", href: "#", price: "1.250.000đ" },
        { id: "p3", title: "Bộ mỹ phẩm chống lão hóa Estee Lauder...", imageUrl: "/assets/p3.png", href: "#", price: "3.500.000đ" },
        { id: "p4", title: "Đồng hồ thông minh định vị trẻ em...", imageUrl: "/assets/p4.png", href: "#", price: "1.890.000đ" },
      ],
      linkGroups: [
        {
          id: "g1",
          title: "Mẹ bầu & Bé sơ sinh",
          href: "#",
          links: [
            { label: "Chuẩn bị mang thai", href: "#" },
            { label: "Mang thai", href: "#" },
            { label: "Chuẩn bị sinh", href: "#" },
            { label: "Trẻ sơ sinh", href: "#" },
            { label: "Trẻ em 5 tháng - 2 tuổi", href: "#" },
          ]
        },
        {
          id: "g2",
          title: "Trẻ em & Thiếu niên",
          href: "#",
          links: [
            { label: "Trẻ em nữ 2-3 tuổi", href: "#" },
            { label: "Trẻ em nam 2-3 tuổi", href: "#" },
            { label: "Trẻ em nữ 5-7 tuổi", href: "#" },
            { label: "Trẻ em nam 5-7 tuổi", href: "#" },
            { label: "Trẻ em nữ 8-10 tuổi", href: "#" },
          ]
        },
        {
          id: "g3",
          title: "Người lớn",
          href: "#",
          links: [
            { label: "Sinh viên", href: "#" },
            { label: "Dành cho Nữ", href: "#" },
            { label: "Dành cho Nam", href: "#" },
            { label: "Quà Biếu Mẹ", href: "#" },
            { label: "Quà biếu Cha", href: "#" },
          ]
        },
        {
          id: "g4",
          title: "Trung niên & Người già",
          href: "#",
          links: [
            { label: "Dành cho Ông", href: "#" },
            { label: "Dành cho Bà", href: "#" },
            { label: "Chăm sóc sức khỏe", href: "#" },
          ]
        },
      ]
    },

    // === TAB 2: NHÂN DỊP ===
    "2": {
      brandLogosTop: [
        { id: "o1", alt: "Kinh Đô", imageUrl: "/assets/logos/iphone.png" },
        { id: "o2", alt: "Danisa", imageUrl: "/assets/logos/samsung.png" },
        { id: "o3", alt: "Ferrero", imageUrl: "/assets/logos/xiaomi.png" },
        { id: "o4", alt: "Orion", imageUrl: "/assets/logos/oppo.png" },
      ],
      featuredProducts: [
        { id: "fp1", title: "Hộp quà Tết Sum Vầy 2025...", imageUrl: "/assets/p1.png", href: "#", price: "850.000đ" },
        { id: "fp2", title: "Bó hoa hồng sáp thơm Valentine...", imageUrl: "/assets/p2.png", href: "#", price: "350.000đ" },
        { id: "fp3", title: "Set quà tân gia Bát Tràng cao cấp...", imageUrl: "/assets/p3.png", href: "#", price: "2.100.000đ" },
        { id: "fp4", title: "Giỏ trái cây nhập khẩu mừng thọ...", imageUrl: "/assets/p4.png", href: "#", price: "1.500.000đ" },
      ],
      linkGroups: [
        {
          id: "h1",
          title: "Ngày lễ lớn (Đầu năm)",
          href: "#",
          links: [
            { label: "Năm mới", href: "#" },
            { label: "14/2 Valentine", href: "#" },
            { label: "8/3 Quốc tế phụ nữ", href: "#" },
            { label: "20/3 Quốc tế hạnh phúc", href: "#" },
            { label: "1/5 Quốc tế lao động", href: "#" },
            { label: "15/5 Quốc tế Gia Đình", href: "#" },
            { label: "1/6 Quốc tế Thiếu Nhi", href: "#" },
          ]
        },
        {
          id: "h2",
          title: "Ngày lễ lớn (Cuối năm)",
          href: "#",
          links: [
            { label: "Lễ Vu Lan (15/7 âm)", href: "#" },
            { label: "Tết Trung Thu (15/8 âm)", href: "#" },
            { label: "20/10 Phụ nữ Việt Nam", href: "#" },
            { label: "20/11 Nhà giáo Việt Nam", href: "#" },
            { label: "25/12 Giáng sinh", href: "#" },
            { label: "Tết Nguyên Đán", href: "#" },
          ]
        },
        {
          id: "h3",
          title: "Sự kiện đặc biệt",
          href: "#",
          links: [
            { label: "Ngày của Mẹ", href: "#" },
            { label: "Ngày của Cha", href: "#" },
            { label: "Ngày Thầy thuốc VN (27/2)", href: "#" },
            { label: "Ngày Doanh nhân VN (13/10)", href: "#" },
            { label: "Ngày Thương binh LS (27/7)", href: "#" },
          ]
        },
        {
          id: "h4",
          title: "Dịp cá nhân & Kỷ niệm",
          href: "#",
          links: [
            { label: "Sinh nhật", href: "#" },
            { label: "Bé chào đời / Thôi nôi", href: "#" },
            { label: "Tốt nghiệp / Tựu trường", href: "#" },
            { label: "Khai trương / Khánh thành", href: "#" },
            { label: "Lễ Đính Hôn / Kỷ niệm cưới", href: "#" },
            { label: "Tân gia / Mừng thọ", href: "#" },
            { label: "Xin lỗi / Chia buồn", href: "#" },
          ]
        },
      ]
    },

    // === TAB 3: BUSINESS GIFTS ===
    "3": {
      brandLogosTop: [
        { id: "bg1", alt: "Parker", imageUrl: "/assets/logos/iphone.png" },
        { id: "bg2", alt: "Moleskine", imageUrl: "/assets/logos/samsung.png" },
        { id: "bg3", alt: "Minh Long", imageUrl: "/assets/logos/xiaomi.png" },
        { id: "bg4", alt: "Lock&Lock Ent", imageUrl: "/assets/logos/oppo.png" },
      ],
      featuredProducts: [
        { id: "bp1", title: "Bút ký cao cấp Parker mạ vàng...", imageUrl: "/assets/p1.png", href: "#", price: "2.500.000đ" },
        { id: "bp2", title: "Bộ Giftset Sổ da & Bút & Bình giữ nhiệt...", imageUrl: "/assets/p2.png", href: "#", price: "850.000đ" },
        { id: "bp3", title: "Cúp vinh danh pha lê khắc laser...", imageUrl: "/assets/p3.png", href: "#", price: "Liên hệ" },
        { id: "bp4", title: "Dù cầm tay in logo doanh nghiệp...", imageUrl: "/assets/p4.png", href: "#", price: "Liên hệ" },
      ],
      linkGroups: [
        {
          id: "b1",
          title: "Quà tặng vinh danh",
          href: "#",
          links: [
            { label: "Cúp vinh danh", href: "#" },
            { label: "Kỷ niệm chương", href: "#" },
            { label: "Huy chương", href: "#" },
            { label: "Cờ đội", href: "#" },
            { label: "Bảng vinh danh, bảng tên", href: "#" },
          ]
        },
        {
          id: "b2",
          title: "Quà tặng doanh nghiệp",
          href: "#",
          links: [
            { label: "Quà tặng tri ân khách hàng", href: "#" },
            { label: "Quà tặng nhân viên", href: "#" },
            { label: "Quà tặng đại hội, hội nghị", href: "#" },
            { label: "Bộ Giftset cao cấp", href: "#" },
          ]
        },
        {
          id: "b3",
          title: "Vật phẩm quảng cáo (POSM)",
          href: "#",
          links: [
            { label: "Mũ bảo hiểm in logo", href: "#" },
            { label: "Ô dù quảng cáo", href: "#" },
            { label: "Áo mưa quảng cáo", href: "#" },
            { label: "Bình giữ nhiệt / Ly sứ", href: "#" },
            { label: "Quà tặng khuyến mại", href: "#" },
          ]
        }
      ]
    },

    // === TAB 4: MẶC ĐỊNH (TƯ VẤN) ===
    "4": {
      brandLogosTop: [],
      featuredProducts: [],
      linkGroups: [
         {
          id: "adv1",
          title: "Gợi ý chọn quà",
          href: "#",
          links: [
            { label: "Cách chọn quà cho bạn gái", href: "#" },
            { label: "Xu hướng quà tết 2025", href: "#" },
            { label: "Nghệ thuật gói quà", href: "#" },
          ]
         }
      ]
    }
  }
};

const randomImages = [
  "/assets/ImageAsset43.png", "/assets/ImageAsset45.png", "/assets/ImageAsset47.png", 
  "/assets/ImageAsset49.png", "/assets/ImageAsset31.png", "/assets/ImageAsset21.png",
  "/assets/ImageAsset11.png", "/assets/ImageAsset1.png"
];

const randomTitles = [
  "Bàn phím cơ không dây E-Dra", "Tai nghe Bluetooth chống ồn", "Chuột Gaming Logitech G102", 
  "Sạc dự phòng 20000mAh", "Loa Bluetooth Mini Bass mạnh", "Đèn bàn học chống cận",
  "Quạt tích điện để bàn", "Giá đỡ điện thoại hợp kim nhôm"
];

export const recommendedData = Array.from({ length: 40 }).map((_, index) => ({
  id: `rec-${index + 1}`,
  image: randomImages[index % randomImages.length],
  title: `${randomTitles[index % randomTitles.length]} - Mẫu mới 2025 (Ver ${index + 1})`,
  price: `${(100 + (index * 15))}.000 VND`,
  sold: `${100 + index * 5}`,
  tag: index % 5 === 0 ? "Yêu thích" : (index % 3 === 0 ? "Mall" : ""),
  discount: index % 4 === 0 ? "-15%" : "",
}));
export * from "./mock-data";